package Vistas;

import Logica.AdministradorDeNiños;
import Logica.NiñoNoExistenteException;
import Logica.ResumenNiño;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

public class ListaControlesDeNiño extends javax.swing.JFrame {
    
    private String idSelected;

    private final AdministradorDeNiños administradorDeNiños;
    private final Object[][] controles;
    private final String documento;

    public ListaControlesDeNiño(AdministradorDeNiños administradorDeNiño, String documento) {
        
        this.administradorDeNiños = administradorDeNiño;
        this.documento = documento;

        this.controles = new Object[this.administradorDeNiños.listar().size()][4];

        int index = 0;
        for (ResumenNiño niño : this.administradorDeNiños.listar()) {
            this.controles[index][0] = niño.getNombre();
            this.controles[index][1] = niño.getDocumento();
            this.controles[index][2] = niño.getServicioDeSalud();
            ++index;
        }
        
        setTitle("Lista de controles de: " + this.controles[0][0]);

        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(dim.width / 2 - getSize().width / 2, dim.height / 2 - getSize().height / 2);

        jTableListaConsultas.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent event) {
                idSelected = jTableListaConsultas.getValueAt(jTableListaConsultas.getSelectedRow(), 1).toString();
                jMenuItemEliminarControl.setEnabled(true);
                jMenuItemModificarControl.setEnabled(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListaConsultas = new javax.swing.JTable();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItemModificarControl = new javax.swing.JMenuItem();
        jMenuItemEliminarControl = new javax.swing.JMenuItem();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de consultas del niño");
        setName("listaNiñosFrame"); // NOI18N

        jTableListaConsultas.setModel(new javax.swing.table.DefaultTableModel(
            this.controles,
            new String [] {
                "Fecha De Registro", "Peso", "Altura"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableListaConsultas);

        jMenu1.setText("Archivo");

        jMenuItem5.setText("Volver al listado de niños");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar.add(jMenu1);

        jMenu2.setText("Controles");

        jMenuItem2.setText("Agregar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItemModificarControl.setText("Modificar");
        jMenuItemModificarControl.setEnabled(false);
        jMenuItemModificarControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModificarControlActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemModificarControl);

        jMenuItemEliminarControl.setText("Eliminar");
        jMenuItemEliminarControl.setEnabled(false);
        jMenuItemEliminarControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarControlActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemEliminarControl);

        jMenuBar.add(jMenu2);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new ListaNiños(administradorDeNiños).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItemEliminarControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarControlActionPerformed
        int input = JOptionPane.showConfirmDialog(null, "¿Estas seguro que deseas eliminar esta consulta?");
        if ( input == 0 ) {
            administradorDeNiños.eliminar(this.idSelected);
        }
    }//GEN-LAST:event_jMenuItemEliminarControlActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new AgregarVacuna(administradorDeNiños, this.documento).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemModificarControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificarControlActionPerformed
        new ModificarVacuna(administradorDeNiños, this.documento, this.idSelected).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenuItemModificarControlActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemEliminarControl;
    private javax.swing.JMenuItem jMenuItemModificarControl;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableListaConsultas;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
